### ISSUE TITLE
The first query to a server gets a timeout

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-cli#17] opened 2015-05-06 14:43 UTC
I get not-so-likely results from using --nstimes:

Testing blipp.com I get this:

    boa.blipp.com/2001:1b40:5600:900:4321:1234:9b92:4bc0  10010.62    31.07   939.99  2868.38    31.43  20679.79

Manual tests from the same machine does not indicate that I would receive any slow responses at all.

Testing iis.se I see something similar:

    ns.nic.se/2a00:801:f0:53::53  10010.63     3.90  1434.30  3501.27     4.79  10040.12

Again, nothing that indicates that something is slow.

Something else that might be broken with this?

**Comment by pawal** [comment] 2015-05-06 15:14
Almost always happens to IPv6 servers for me. All three at dns-oarc.net showed the same thing. The only reason I get timeouts using dig is when using larger bufsizes.

Reading the logs from the above tests always gives a "network error" indicating the timeout on the first query. So I am not sure what is happening here. Is the first query using a larger bufsize, or what could be the reason for the initial timeouts?

**Comment by sandoche2k** [comment] 2015-05-17 14:58
@vlevigneron will you be able to have a look at it. If yes, please provide which release you will be able to do it? .2 or .3?
@pawal - If VLE agrees, assign it to him

**Comment by pawal** [comment] 2015-06-02 12:49
Ping @vlevigneron - still on vacation? ;)

**Comment by vlevigneron** [comment] 2015-06-02 12:55
Just came back yesterday... :-)

Plan to look at it this week.


le 02 juin, Patrik Wallström a ?crit :
> Ping @vlevigneron - still on vacation? ;)
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dotse/zonemaster-cli/issues/17#issuecomment-107942985

-- 
	Vincent Levigneron  A.F.N.I.C.  Vincent.Levigneron@nic.fr

**Comment by cdybedahl** [comment] 2015-06-03 12:37
I can't reproduce this on OS X or FreeBSD. Which OS(s) did you see it on?

It's difficult to imagine something in our code that could have this effect, given that all outgoing queries follow exactly the same code path at least down into the ldns networking code.

**Comment by pawal** [comment] 2015-06-04 08:23
I use Debian 8. However, there could be tunnels, NAT and such doing this. I could try to look at the behaviour on another machine soon.

**Comment by cdybedahl** [comment] 2015-06-04 12:48
To be a bit more specifik, I've tried from OS X on a Macbook Pro using a HE tunnel, and from FreeBSD on a VMWare cluster using native IPv6 supplied by GleSYS.

**Comment by cdybedahl** [comment] 2015-06-04 13:22
I *can* see similar behavior against an *IPv4* address when running from a Debian 7 machine in an OpenVZ cluster, while testing the `dns-oarc.net` zone. This does not make me less inclined to think that this is a Linux problem.

**Comment by sandoche2k** [comment] 2015-06-05 08:36
@pawal is it similar to issue #20 ?

**Comment by cdybedahl** [comment] 2015-06-05 08:40
No, they are completely different. #20 was a plain oversight on my part when writing the code.

**Comment by sandoche2k** [comment] 2015-09-22 14:03
@pawal are we able to reproduce the issue ?

**Closed** 2015-10-09 08:38 UTC
Labels: bug
